### PR TITLE
Say goodbye to blocking portal

### LINKED ISSUE #72: option to not use the blocking portal
## Describe the bug

In our use, it is important to run the tested app in the same event loop as the testing fixtures.

(Basically we preinitialise stuff for the app and that happens in the event loop supplied by pytest. Then we need to keep everything on this loop so that cleanup works correctly. We have run into issues when doing this with redis or database connections).

## Expected behavior

Replacing the blocking portal with asyncio.create_task fixes the issues for us.

Making the blocking portal optional could be the solution that works for everyone.

Here is a patch that does that:
[optional.blocking.portal.patch](https://github.com/user-attachments/files/16069192/optional.blocking.portal.patch)

## Configuration
 - Python version: 3.11
 - httpx-ws version: 0.6

### PR DESCRIPTION
**Pull request by GreyElaina**
I'm not sure if it's right, but it works.

Close #72

### CODE REVIEW

**Comment by frankie567** [comment]
Wow, could it be *that* simple? 😄 I'm surprised but, well, tests are passing properly so... Let's go for it 👍 

@all-contributors add @GreyElaina for code

**Comment by frankie567** [comment]
@all-contributors add @GreyElaina for code

**Comment by agronholm** [comment]
If the task group is the only thing you `__aenter__` and `__aexit__`, what do you need the exit stack for?

**Comment by GreyElaina** [comment]
> If the task group is the only thing you `__aenter__` and `__aexit__`, what do you need the exit stack for?

🤔 anyio's TaskGroup behaviors odd and just make it work.

**Comment by agronholm** [comment]
What do you mean by "odd"? I wrote that code.

**Comment by GreyElaina** [comment]
> What do you mean by "odd"? I wrote that code.

at first i tried call `__aexit__(None, None, None)` in the `aclose` method, then it said CancelScope differs("Attempted to exit a cancel scope that isn't the current tasks's current cancel scope"). after i check the usage of `aclose` method, i choose current way.

Glad to listen your explain, sir.

**Pull request merged**
