### PR TITLE
Allow use custom session class

### LINKED ISSUE #87: Allow to pass a custom session class to `connect_ws`/`aconnect_ws`
### Discussed in https://github.com/frankie567/httpx-ws/discussions/86

Instead of exposing a specific argument just for `ping`, what would you think about the possibility to pass directly websocket session class as argument of `aconnect_ws`? In your case, it would look like this:

```py
class CustomPingAsyncWebSocketSession(AsyncWebSocketSession):
    async def ping(self, payload: bytes = b"custom_ping_payload") -> anyio.Event:
        return await super().ping(payload)

async with aconnect_ws("http://localhost:8000/ws", session_class=CustomPingAsyncWebSocketSession) as ws:
    message = await ws.receive_text()
```

### PR DESCRIPTION
**Pull request by GreyElaina**
Close #87

### CODE REVIEW

**Review by frankie567 — CHANGES_REQUESTED** [review]
Looks great, thank you 👍 May I ask you to add the docstrings for those parameters? 🙏

**Comment by GreyElaina** [comment]
done

**Comment by GreyElaina** [comment]
Seems mypy rejects my typing, although i was battle hardened with pyright to force it go on my expected way.

**Comment by frankie567** [comment]
Yes, that's a bit unexpected, I'll have a closer look

**Comment by frankie567** [comment]
Ended up adding a `# type: ignore` 😅

**Pull request merged**
