### PR TITLE
Add `response` attribute for `WebSocketSession`

### PR DESCRIPTION
**Pull request by WSH032**
Close: [discussions/53](https://github.com/frankie567/httpx-ws/discussions/53)

### CODE REVIEW

**Comment by WSH032** [comment]
I have an idea, what about using `response` instead of `subprotocol` as the parameter?

```python
class AsyncWebSocketSession:
    response: httpx.Response
    subprotocol: typing.Optional[str]

    def __init__(
        self,
        stream: AsyncNetworkStream,
        *,
        response: httpx.Response,
        max_message_size_bytes: int = DEFAULT_MAX_MESSAGE_SIZE_BYTES,
        queue_size: int = DEFAULT_QUEUE_SIZE,
        keepalive_ping_interval_seconds: typing.Optional[
            float
        ] = DEFAULT_KEEPALIVE_PING_INTERVAL_SECONDS,
        keepalive_ping_timeout_seconds: typing.Optional[
            float
        ] = DEFAULT_KEEPALIVE_PING_TIMEOUT_SECONDS,
        # subprotocol: typing.Optional[str] = None,  # delete
    ) -> None:
        self.stream = stream
        self.connection = wsproto.connection.Connection(wsproto.ConnectionType.CLIENT)
        self.response = response
        self.subprotocol = response.headers.get("sec-websocket-protocol")  # instead
```

Explicitly annotating `httpx.Response` instead of `typing.Optional[httpx.Response]` can provide type checking benefits to prevent type checking complaints about `ws.Response` being None.

**Comment by WSH032** [comment]
Hi @frankie567 

Can you review this PR? I'm maintaining [fastapi-proxy-lib](https://github.com/WSH032/fastapi-proxy-lib/), which uses `httpx-ws` as the underlying library to implement reverse proxy functionality. I'm hoping to be able to retrieve response headers through `httpx-ws`, so that I can achieve transparent proxying.

https://github.com/WSH032/fastapi-proxy-lib/blob/977d9c10c102c4dd34101f0f9eb51de6cba72a70/src/fastapi_proxy_lib/core/websocket.py#L571-L573

**Comment by frankie567** [comment]
Hey @WSH032 👋 

Sorry, this got out of my mind 😊

Looks good overall! I would be indeed interested in having the `subprotocol` pulled from the `response` parameter, if available.

However, let's keep `response` typed as `Optional`, as it would be painful for testing.

**Review by frankie567 — CHANGES_REQUESTED** [review]
Hey @WSH032 👋

Sorry, this got out of my mind 😊

Looks good overall! I would be indeed interested in having the subprotocol pulled from the response parameter, if available.

However, let's keep response typed as Optional, as it would be painful for testing.

**Comment by WSH032** [comment]
For the current PR, the type of `response` is indeed `Optional`. Is there anything you would like me to change? Or do we need to wait for something?

**Comment by frankie567** [comment]
Just the way we set `self.subprotocol`: let's use the response object if available instead of explicitly passing it in argument.

**Comment by WSH032** [comment]
Sorry, please forgive me. Could you clarify further? I'm not quite understanding.

We're only passing `response` in `aconnect_ws`. Wouldn't this cause a `WebSocketUpgradeError` if `response` isn't available?

**Comment by frankie567** [comment]
Yes, sorry, I'm not being clear here. What I mean is, I would like to do this:

```py
class AsyncWebSocketSession:
    subprotocol: typing.Optional[str]

    def __init__(
        self,
        stream: AsyncNetworkStream,
        *,
        max_message_size_bytes: int = DEFAULT_MAX_MESSAGE_SIZE_BYTES,
        queue_size: int = DEFAULT_QUEUE_SIZE,
        keepalive_ping_interval_seconds: typing.Optional[
            float
        ] = DEFAULT_KEEPALIVE_PING_INTERVAL_SECONDS,
        keepalive_ping_timeout_seconds: typing.Optional[
            float
        ] = DEFAULT_KEEPALIVE_PING_TIMEOUT_SECONDS,
        response: typing.Optional[httpx.Response] = None,
    ) -> None:
        self.stream = stream
        self.connection = wsproto.connection.Connection(wsproto.ConnectionType.CLIENT)
        self.response = response
        if self.response is not None:
            self.subprotocol = response.headers.get("sec-websocket-protocol")
        else:
            self.subprotocol = None
```

And so `_aconnect_ws` (and `_connect_ws`) would look like this:

```py
@contextlib.asynccontextmanager
async def _aconnect_ws(
    url: str,
    client: httpx.AsyncClient,
    *,
    max_message_size_bytes: int = DEFAULT_MAX_MESSAGE_SIZE_BYTES,
    queue_size: int = DEFAULT_QUEUE_SIZE,
    keepalive_ping_interval_seconds: typing.Optional[
        float
    ] = DEFAULT_KEEPALIVE_PING_INTERVAL_SECONDS,
    keepalive_ping_timeout_seconds: typing.Optional[
        float
    ] = DEFAULT_KEEPALIVE_PING_TIMEOUT_SECONDS,
    subprotocols: typing.Optional[typing.List[str]] = None,
    **kwargs: typing.Any,
) -> typing.AsyncGenerator[AsyncWebSocketSession, None]:
    headers = kwargs.pop("headers", {})
    headers.update(_get_headers(subprotocols))

    async with client.stream("GET", url, headers=headers, **kwargs) as response:
        if response.status_code != 101:
            raise WebSocketUpgradeError(response)

        async with AsyncWebSocketSession(
            response.extensions["network_stream"],
            max_message_size_bytes=max_message_size_bytes,
            queue_size=queue_size,
            keepalive_ping_interval_seconds=keepalive_ping_interval_seconds,
            keepalive_ping_timeout_seconds=keepalive_ping_timeout_seconds,
            response=response,
        ) as session:
            yield session
```

Said another way, the "parsing" of the subprotocol is done by the main class instead of the context manager function.

**Comment by WSH032** [comment]
Oh, I see what you mean now. I've made the changes accordingly. But this seems like a BREAKING CHANGE, doesn't it?

**Comment by frankie567** [comment]
Indeed, but I don't expect much people to use the class directly; so that's acceptable if clearly stated in the changelog 😄

**Comment by frankie567** [comment]
@all-contributors add @WSH032 for code

**Pull request merged**
