### PR TITLE
#2 Add ping method

### PR DESCRIPTION
**Pull request by kousikmitra**

### CODE REVIEW

**Comment by kousikmitra** [comment]
fixed lint issue

**Comment by frankie567** [comment]
Looks good, @kousikmitra, thanks 🙏  May I ask you to add `payload` as an optional parameter and forward it to the event initializer? Something like:

```py
def ping(self, payload: typing.Optional[bytes] = None) -> None:
        event = wsproto.events.Ping(payload)
        self._send_event(event)
```

**Comment by kousikmitra** [comment]
> Looks good, @kousikmitra, thanks 🙏 May I ask you to add `payload` as an optional parameter and forward it to the event initializer? Something like:
> 
> ```python
> def ping(self, payload: typing.Optional[bytes] = None) -> None:
>         event = wsproto.events.Ping(payload)
>         self._send_event(event)
> ```

done, changed the func signature to `ping(self, payload: bytes = b"") ` as Ping doesn't take None

**Comment by frankie567** [comment]
> done, changed the func signature to `ping(self, payload: bytes = b"") ` as Ping doesn't take None

Indeed, perfectly right! LGTM!

@all-contributors add @frankie567 for maintenance, @kousikmitra for code

**Comment by frankie567** [comment]
Yes, but now, @all-contributors add @kousikmitra for code

**Pull request merged**
